#! /bin/sh

########################
# Launch hotkey daemon #
########################
pgrep -x sxhkd > /dev/null || sxhkd &


##########################
# Monitors and statusbar #
##########################
killall -q polybar
if  xrandr | grep -q "HDMI-1-0 d"; then
    xrandr --output "HDMI-1-0" --off
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
    polybar --reload -c ~/.config/polybar/config_bspwm mainbar &
else
    xrandr --output "HDMI-1-0" --above "eDP-1" --auto
    bspc monitor "eDP-1" -d 1 3 5
    bspc monitor "HDMI-1-0" -d 2 4 6 7 8 9 10
    polybar --reload -c ~/.config/polybar/config_bspwm top_bar &
    polybar --reload -c ~/.config/polybar/config_bspwm bottom_bar &
fi


###########
# Borders #
###########
bspc config border_width 1
bspc config focused_border_color '#b55fd4'


########
# Gaps #
########
bspc config window_gap 10


##########
# Splits #
##########
bspc config split_ratio 0.5


#########
# Focus #
#########
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true


##############
# Compositor #
##############
picom --config ~/.config/bspwm/picom.conf &


#############
# Autostart #
#############
numlockx on
xset r rate 220 35
setxkbmap -option caps:swapescape
feh --bg-fill ~/Pictures/celeste.png &
pgrep -x nm-applet > /dev/null || nm-applet &
pgrep -x spotify > /dev/null || spotify &
pgrep -x discord > /dev/null || discord &
pgrep -x thunderbird > /dev/null || thunderbird &
pgrep -x flameshot > /dev/null || flameshot &


#########
# Rules #
#########
bspc rule -a Spotify desktop='10'
bspc rule -a discord desktop='9'
bspc rule -a Thunderbird desktop='8'
bspc rule -a teams desktop='7'

bspc rule -a Galculator state=floating
bspc rule -a Gpick state=floating
bspc rule -a Font-manager state=floating
bspc rule -a qt5ct state=floating
bspc rule -a lxappearance state=floating
bspc rule -a Pavucontrol state=floating

bspc rule -a Zathura state=tiled
